#!/bin/sh

case "$1" in
        start)
                echo "Starting aesdsocket"
                cd /lib/modules/$(uname -r)/extra
                ./aesdchar_load
                start-stop-daemon -S -n aesdsocket -a /usr/bin/aesdsocket -- -d
                ;;
        stop)
                echo "Stoping aesdsocket"
                start-stop-daemon -K -n aesdsocket
                cd /lib/modules/$(uname -r)/extra
                ./aesdchar_unload
                ;;
        restart|reload)
                "$0" stop
                "$0" start
                ;;
        *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
esac

exit $?