#!/bin/sh

case "$1" in
        start)
                echo "Starting aesdsocket"
                start-stop-daemon -S -n aesdsocket -a /usr/bin/aesdsocket -- -d
                ;;
        stop)
                echo "Stoping aesdsocket"
                start-stop-daemon -K -n aesdsocket
                ;;
        restart|reload)
                "$0" stop
                "$0" start
                ;;
        *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
esac

exit $?